variables:
  Agent.Source.Git.ShallowFetchDepth: 0

steps:
- checkout: self

- script: /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=/usr/local/lib/android/sdk \"platform-tools\"

- powershell: .\build.ps1
  env:
    NuGetApiKey: $(NuGetApiKey)